### ISSUE TITLE
Read region fails for iSyntax using OpenSlide Python

### ISSUE THREAD

**Issue by codybum** [innovationcore/openslide#1]
## Context

**Issue type** 
Bug Report

**Operating system** 
Mac OS 11.6.2

**Platform** 
64-bit x86 

**OpenSlide version**
OpenSlide: https://github.com/innovationcore/openslide/commit/f1e1ea84eafa498c3a6c5d29288589a600eb9085
OpenSlide Python: 1.2.0

**Slide format** iSyntax

## Details

Reading slide data from OpenSlide Python [1] results in error [2].

[1] https://github.com/ukpathologyinformatics/digitalpathprocessor/blob/master/iSyntaxTest.py

[2]
philips_isyntax_open: Opening file deident.isyntax
VERBOSE isyntax_open:2247: Attempting to open iSyntax: deident.isyntax
...
philips_isyntax_read_tile: ### isyntax_load_tile(x=11, y=15)
**
Openslide:ERROR:src/openslide-vendor-philips-isyntax.c:168:philips_isyntax_read_tile: assertion failed: (tiledata != NULL)
Bail out! Openslide:ERROR:src/openslide-vendor-philips-isyntax.c:168:philips_isyntax_read_tile: assertion failed: (tiledata != NULL)
zsh: abort      python iSyntaxTest.py

**Comment by alex-virodov** [comment]
Fixed. I added the python openslide test script to this repo (not auto-tested yet).
